name:                blackjack-haskell
version:             0.1.0.0
github:              "jarlah/blackjack-haskell"
license:             BSD3
author:              "jarlah"
maintainer:          "jarlah"
copyright:           "2019-2026 jarlah"

extra-source-files:
- README.md
- ChangeLog.md

description:         A simple blackjack card game in Haskell

dependencies:
- base >= 4.7 && < 5
- random >= 1.1

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - brick
  - vty

executables:
  blackjack-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - blackjack-haskell
    - brick
    - vty

tests:
  blackjack-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - blackjack-haskell
    - hspec
